/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef res_CONSTANTS_H
#define res_CONSTANTS_H

#include "res_types.h"

namespace res_pd_rpc {

class resConstants {
 public:
  resConstants();

};

extern const resConstants g_res_constants;

} // namespace

#endif
