/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef p4_pd_rpc_CONSTANTS_H
#define p4_pd_rpc_CONSTANTS_H

#include "p4_pd_rpc_types.h"

namespace p4_pd_rpc {

class p4_pd_rpcConstants {
 public:
  p4_pd_rpcConstants();

};

extern const p4_pd_rpcConstants g_p4_pd_rpc_constants;

} // namespace

#endif
