/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "p4_pd_rpc_constants.h"

namespace p4_pd_rpc {

const p4_pd_rpcConstants g_p4_pd_rpc_constants;

p4_pd_rpcConstants::p4_pd_rpcConstants() {
}

} // namespace

