/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "res_constants.h"

namespace res_pd_rpc {

const resConstants g_res_constants;

resConstants::resConstants() {
}

} // namespace

