DIRNAME="netreach-v4"
REMOTEPATH="~/NetBuffer"
REMOTEHOST="ssy@bf1"
ssh $REMOTEHOST "rm -rf $REMOTEPATH/$DIRNAME"
scp -r ./$DIRNAME $REMOTEHOST:$REMOTEPATH/$DIRNAME

DIRNAME="netreach-v4"
REMOTEPATH="~/projects/NetBuffer"
REMOTEHOST="ssy@dl13"
ssh $REMOTEHOST "rm -rf $REMOTEPATH/$DIRNAME"
scp -r ./$DIRNAME $REMOTEHOST:$REMOTEPATH/$DIRNAME
