# Global information unchanged during experiments

USER="ssy"

SWITCH_PRIVATEKEY=".ssh/switch-private-key"
CONNECTION_PRIVATEKEY=".ssh/connection-private-key"

MAIN_CLIENT="dl11" # used in recovery mode
SECONDARY_CLIENT="dl20"

# NOTE: must be consistent with each config.ini
SERVER0="dl21"
SERVER1="dl30"

LEAFSWITCH="bf3"
# NOTE:SPINESWITCH is not used at this stage
# SPINESWITCH="bf3" 

CLIENT_ROOTPATH="/home/${USER}/projects/farreach-private"
SWITCH_ROOTPATH="/home/${USER}/farreach-private"
SERVER_ROOTPATH="/home/${USER}/projects/farreach-private"

# backup rocksdb after loading phase
BACKUPS_ROOTPATH="/tmp/rocksdbbackups"

# experiment
EVALUATION_SCRIPTS_PATH="${CLIENT_ROOTPATH}/scripts"
EVALUATION_OUTPUT_PREFIX="/home/${USER}/results"

# network settings

MAIN_CLIENT_TOSWITCH_IFNAME="enp129s0f0"
MAIN_CLIENT_TOSWITCH_IP="10.0.1.11"
MAIN_CLIENT_TOSWITCH_MAC="3c:fd:fe:bb:ca:78"
MAIN_CLIENT_TOSWITCH_FPPORT="5\/0"
MAIN_CLIENT_TOSWITCH_PIPEIDX="1"
MAIN_CLIENT_LOCAL_IP="172.16.112.11"

SECONDARY_CLIENT_TOSWITCH_IFNAME="ens2f0"
SECONDARY_CLIENT_TOSWITCH_IP="10.0.1.20"
SECONDARY_CLIENT_TOSWITCH_MAC="9c:69:b4:60:34:f4"
SECONDARY_CLIENT_TOSWITCH_FPPORT="21\/0"
SECONDARY_CLIENT_TOSWITCH_PIPEIDX="0"
SECONDARY_CLIENT_LOCAL_IP="172.16.112.20"

SERVER0_TOSWITCH_IFNAME="ens2f1"
SERVER0_TOSWITCH_IP="10.0.1.21"
SERVER0_TOSWITCH_MAC="9c:69:b4:60:34:e1"
SERVER0_TOSWITCH_FPPORT="6\/0"
SERVER0_TOSWITCH_PIPEIDX="1"
SERVER0_LOCAL_IP="172.16.112.21"

SERVER1_TOSWITCH_IFNAME="ens3f1"
SERVER1_TOSWITCH_IP="10.0.1.30"
SERVER1_TOSWITCH_MAC="9c:69:b4:60:ef:c1"
SERVER1_TOSWITCH_FPPORT="3\/0"
SERVER1_TOSWITCH_PIPEIDX="1"
SERVER1_LOCAL_IP="172.16.112.30"

CONTROLLER_LOCAL_IP="172.16.112.21"
SWITCHOS_LOCAL_IP="172.16.112.19"
SWITCH_RECIRPORT_PIPELINE1TO0="7\/0"
SWITCH_RECIRPORT_PIPELINE0TO1="12\/0"

# CPU settings

SERVER0_WORKER_CORENUM="16"
SERVER0_TOTAL_CORENUM="48"
SERVER1_WORKER_CORENUM="16"
SERVER1_TOTAL_CORENUM="72"

is_global_included=1
