
for i in range(1,17):
    for tag in ['lo','hi']:
        print('Register<bit<32>,bit<32>>(KV_BUCKET_COUNT) val'+tag+str(i)+'_reg;')
        print('RegisterAction<bit<32>, bit<32>, bit<32>>(val'+tag+str(i)+'_reg) val'+tag+str(i)+'_reg_get_alu = {')
        print('    void apply(inout bit<32> register_data, out bit<32> result) {')
        print('        result = register_data;')
        print('    }')
        print('};')
        print('RegisterAction<bit<32>, bit<32>, bit<32>>(val'+tag+str(i)+'_reg) val'+tag+str(i)+'_reg_set_alu = {')
        print('    void apply(inout bit<32> register_data, out bit<32> result) {')
        print('        register_data = hdr.val'+str(i)+'_hdr.val'+tag+';')
        print('    }')
        print('};')
        print('')
        print('action get_val'+tag+str(i)+'() {')
        print('    hdr.val'+str(i)+'_hdr.val'+tag+' = val'+tag+str(i)+'_reg_get_alu.execute((bit<32>)hdr.inswitch_hdr.idx);')
        print('}')
        print('')
        print('action set_and_get_val'+tag+str(i)+'() {')
        print('    val'+tag+str(i)+'_reg_set_alu.execute((bit<32>)hdr.inswitch_hdr.idx);')
        print('}')
        print('')
        print('action reset_and_get_val'+tag+str(i)+'() {')
        print('    hdr.val'+str(i)+'_hdr.val'+tag+' = 0;')
        print('    val'+tag+str(i)+'_reg_set_alu.execute((bit<32>)hdr.inswitch_hdr.idx);')
        print('}')
        print('table update_val'+tag+str(i)+'_tbl {')
        print('    key = {')
        print('        meta.access_val_mode: exact;')
        print('    }')
        print('    actions = {')
        print('        get_val'+tag+str(i)+';')
        print('        set_and_get_val'+tag+str(i)+';')
        print('        reset_and_get_val'+tag+str(i)+';')
        print('        NoAction;')
        print('    }')
        print('    default_action = NoAction();')
        print('    size = 32;')
        print('}')